"use client";

import Link from "next/link";
import { useState } from "react";

import { PageHeader } from "@/components/PageHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { basisPointsToPercent, percentToBasisPoints } from "@/lib/admin-catalog-units";
import type { BillingV2AdminCommitment } from "@/lib/internal-api";
import { CatalogFeedback, CatalogField, CatalogNavigation, CatalogTabs, CatalogToggle, ImmutableCode, StickyActions, adminCatalogStyles as styles, useUnsavedChangesGuard } from "./AdminCatalogUi";
import { useAdminCatalogCommand } from "./useAdminCatalogCommand";

type Tab = "essential" | "payments";
type Draft = { name: string; commitmentMonths: number; discountPercent: string; allowMonthlyPayment: boolean; allowUpfrontPayment: boolean; status: string; displayOrder: number };

export function CommitmentCatalogEditor({ commitment, tab }: { commitment: BillingV2AdminCommitment; tab: Tab }) {
  const initial: Draft = { name: commitment.name, commitmentMonths: commitment.commitmentMonths, discountPercent: basisPointsToPercent(commitment.discountBasisPoints ?? 0), allowMonthlyPayment: commitment.allowMonthlyPayment, allowUpfrontPayment: commitment.allowUpfrontPayment, status: commitment.status, displayOrder: commitment.displayOrder };
  const [draft, setDraft] = useState(initial); const [saved, setSaved] = useState(initial); const [validation, setValidation] = useState<string | null>(null);
  const dirty = JSON.stringify(draft) !== JSON.stringify(saved); const command = useAdminCatalogCommand(); const base = `/admin/catalog/engagements/${commitment.id}`;
  const tabs = [{ key: "essential", label: "Essentiel", href: `${base}?tab=essential` }, { key: "payments", label: "Règlement et remises", href: `${base}?tab=payments` }];
  useUnsavedChangesGuard(dirty);
  async function save(event: React.FormEvent) { event.preventDefault(); const discountBasisPoints = percentToBasisPoints(draft.discountPercent); if (discountBasisPoints === null) { setValidation("La remise doit être comprise entre 0 % et 100 %, avec deux décimales maximum."); return; } setValidation(null); if (await command.send({ kind: "commitment.update", id: commitment.id, name: draft.name, commitmentMonths: draft.commitmentMonths, allowMonthlyPayment: draft.allowMonthlyPayment, allowUpfrontPayment: draft.allowUpfrontPayment, status: draft.status, displayOrder: draft.displayOrder, discountBasisPoints })) setSaved(draft); }
  return <div className={styles.shell}><PageHeader eyebrow="Catalogue · Engagement" title={commitment.name} description="Durée, modes de règlement et remises appliquées par le moteur Billing V2." action={<Link className="button button-secondary" href="/admin/catalog?section=engagements">Retour aux engagements</Link>} /><CatalogNavigation active="engagements" /><CatalogTabs active={tab} tabs={tabs} /><CatalogFeedback feedback={command.feedback} />
    {tab === "essential" ? <form onSubmit={save}><section className={styles.panel}><div className={styles.sectionHeading}><div><h2>Informations essentielles</h2><p>Le code reste stable ; les options par mode portent les remises réellement proposées au devis.</p></div></div>{validation ? <p className={`${styles.notice} ${styles.dangerNotice}`}>{validation}</p> : null}<ImmutableCode value={commitment.code} /><div className={styles.formGrid} style={{ marginTop: 16 }}><CatalogField htmlFor="commitment-name" label="Nom"><input id="commitment-name" maxLength={160} onChange={(e) => setDraft({ ...draft, name: e.currentTarget.value })} required value={draft.name} /></CatalogField><CatalogField htmlFor="commitment-months" label="Durée (mois)"><input id="commitment-months" max={120} min={1} onChange={(e) => setDraft({ ...draft, commitmentMonths: Number(e.currentTarget.value) })} type="number" value={draft.commitmentMonths} /></CatalogField><CatalogField htmlFor="commitment-status" label="Statut"><select id="commitment-status" onChange={(e) => setDraft({ ...draft, status: e.currentTarget.value })} value={draft.status}><option value="active">Actif</option><option value="inactive">Inactif</option></select></CatalogField><CatalogField htmlFor="commitment-order" label="Ordre"><input id="commitment-order" min={0} onChange={(e) => setDraft({ ...draft, displayOrder: Number(e.currentTarget.value) })} type="number" value={draft.displayOrder} /></CatalogField><CatalogToggle checked={draft.allowMonthlyPayment} description="Autorise une option de paiement mensuel." label="Paiement mensuel autorisé" name="monthly" onChange={(value) => setDraft({ ...draft, allowMonthlyPayment: value })} /><CatalogToggle checked={draft.allowUpfrontPayment} description="Autorise une option de paiement comptant." label="Paiement comptant autorisé" name="upfront" onChange={(value) => setDraft({ ...draft, allowUpfrontPayment: value })} /></div><div className={styles.advanced}><h3>Paramètres avancés</h3><CatalogField htmlFor="commitment-default-discount" label="Remise générale (%)" hint="Conservée dans le modèle. Le devis public applique la remise de l’option de règlement sélectionnée."><input id="commitment-default-discount" inputMode="decimal" onChange={(e) => setDraft({ ...draft, discountPercent: e.currentTarget.value })} value={draft.discountPercent} /></CatalogField></div></section><StickyActions busy={command.busy} dirty={dirty} onCancel={() => setDraft(saved)} /></form> : null}
    {tab === "payments" ? <PaymentOptions command={command} commitment={commitment} /> : null}
  </div>;
}

function PaymentOptions({ command, commitment }: { command: ReturnType<typeof useAdminCatalogCommand>; commitment: BillingV2AdminCommitment }) {
  const [mode, setMode] = useState<"monthly" | "upfront" | null>(null);
  const [discount, setDiscount] = useState("0"); const [status, setStatus] = useState("active"); const [order, setOrder] = useState(0); const [validation, setValidation] = useState<string | null>(null);
  function beginEdit(paymentMode: "monthly" | "upfront") { const option = commitment.paymentOptions.find((item) => item.paymentMode === paymentMode); setDiscount(basisPointsToPercent(option?.discountBasisPoints ?? 0)); setStatus(option?.status ?? "active"); setOrder(option?.displayOrder ?? 0); setValidation(null); setMode(paymentMode); }
  async function save(event: React.FormEvent) { event.preventDefault(); const discountBasisPoints = percentToBasisPoints(discount); if (!mode || discountBasisPoints === null) { setValidation("La remise doit être comprise entre 0 % et 100 %."); return; } setValidation(null); if (await command.send({ kind: "commitment.payment_option", id: commitment.id, paymentMode: mode, discountBasisPoints, status, displayOrder: order })) setMode(null); }
  return <section className={styles.panel}><div className={styles.sectionHeading}><div><h2>Règlement et remises</h2><p>Les pourcentages sont convertis exactement en points de base avant envoi au BFF.</p></div></div><div className={styles.integrationGrid}>{(["monthly", "upfront"] as const).map((paymentMode) => { const current = commitment.paymentOptions.find((entry) => entry.paymentMode === paymentMode); const allowed = paymentMode === "monthly" ? commitment.allowMonthlyPayment : commitment.allowUpfrontPayment; return <article className={styles.integrationCard} key={paymentMode}><StatusBadge label={current?.status === "active" && allowed ? "Disponible" : "Indisponible"} tone={current?.status === "active" && allowed ? "success" : "neutral"} /><h2>{paymentMode === "monthly" ? "Paiement mensuel" : "Paiement comptant"}</h2><strong className={styles.priceAmount}>{basisPointsToPercent(current?.discountBasisPoints ?? 0)} %</strong><p className={styles.hint}>{allowed ? "Mode autorisé par l’engagement." : "Mode désactivé dans les informations essentielles."}</p><button className="button button-secondary" onClick={() => beginEdit(paymentMode)} type="button">Configurer</button></article>; })}</div>{mode ? <form className={styles.inlineForm} onSubmit={save}><div className={styles.fieldFull}><h3>{mode === "monthly" ? "Paiement mensuel" : "Paiement comptant"}</h3>{validation ? <p className={`${styles.notice} ${styles.dangerNotice}`}>{validation}</p> : null}</div><CatalogField htmlFor="option-discount" label="Remise (%)"><input id="option-discount" inputMode="decimal" onChange={(e) => setDiscount(e.currentTarget.value)} value={discount} /></CatalogField><CatalogField htmlFor="option-status" label="Statut"><select id="option-status" onChange={(e) => setStatus(e.currentTarget.value)} value={status}><option value="active">Actif</option><option value="inactive">Inactif</option></select></CatalogField><CatalogField htmlFor="option-order" label="Ordre"><input id="option-order" min={0} onChange={(e) => setOrder(Number(e.currentTarget.value))} type="number" value={order} /></CatalogField><div className={`${styles.fieldFull} ${styles.actionGroup}`}><button className="button button-secondary" onClick={() => setMode(null)} type="button">Annuler</button><button className="button" disabled={command.busy} type="submit">Enregistrer l’option</button></div></form> : null}</section>;
}
