"use client";

import Link from "next/link";
import { useState } from "react";

import { PageHeader } from "@/components/PageHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { formatCurrencyFromCents } from "@/lib/formatters";
import type { BillingV2AdminPreset, BillingV2AdminPresetItem, BillingV2AdminService } from "@/lib/internal-api";
import { CatalogFeedback, CatalogField, CatalogNavigation, CatalogTabs, CatalogToggle, ImmutableCode, StickyActions, adminCatalogStyles as styles, useUnsavedChangesGuard } from "./AdminCatalogUi";
import { useAdminCatalogCommand } from "./useAdminCatalogCommand";

type Tab = "essential" | "composition" | "preview";
type Draft = { name: string; description: string; status: string; isPublic: boolean; displayOrder: number };
type ItemDraft = { serviceId: string; tierId: string; scopeTemplate: string; quantity: number; requiredItem: boolean; customerEditable: boolean; displayOrder: number };

export function FormulaCatalogEditor({ baselineMonthlyAmountCents, preset, services, tab }: { baselineMonthlyAmountCents: number | null; preset: BillingV2AdminPreset; services: BillingV2AdminService[]; tab: Tab }) {
  const initial: Draft = { name: preset.name, description: preset.description ?? "", status: preset.status, isPublic: preset.isPublic, displayOrder: preset.displayOrder };
  const [draft, setDraft] = useState(initial); const [saved, setSaved] = useState(initial);
  const dirty = JSON.stringify(draft) !== JSON.stringify(saved); const command = useAdminCatalogCommand();
  const base = `/admin/catalog/formules/${preset.id}`;
  const tabs = [{ key: "essential", label: "Essentiel", href: `${base}?tab=essential` }, { key: "composition", label: "Composition", href: `${base}?tab=composition` }, { key: "preview", label: "Aperçu commercial", href: `${base}?tab=preview` }];
  useUnsavedChangesGuard(dirty);
  async function save(event: React.FormEvent) { event.preventDefault(); if (await command.send({ kind: "preset.update", id: preset.id, ...draft })) setSaved(draft); }
  return <div className={styles.shell}><PageHeader eyebrow="Catalogue · Formule" title={preset.name} description="Une formule compose des services ; son prix reste calculé par Billing V2." action={<Link className="button button-secondary" href="/admin/catalog?section=formules">Retour aux formules</Link>} /><CatalogNavigation active="formules" /><CatalogTabs active={tab} tabs={tabs} /><CatalogFeedback feedback={command.feedback} />
    {tab === "essential" ? <form onSubmit={save}><section className={styles.panel}><div className={styles.sectionHeading}><div><h2>Informations essentielles</h2><p>Identité, publication et ordre de présentation de la formule.</p></div></div><ImmutableCode value={preset.code} /><div className={styles.formGrid} style={{ marginTop: 16 }}><CatalogField htmlFor="preset-name" label="Nom"><input id="preset-name" maxLength={160} onChange={(e) => setDraft({ ...draft, name: e.currentTarget.value })} required value={draft.name} /></CatalogField><CatalogField htmlFor="preset-status" label="Statut"><select id="preset-status" onChange={(e) => setDraft({ ...draft, status: e.currentTarget.value })} value={draft.status}><option value="active">Active</option><option value="inactive">Inactive</option></select></CatalogField><CatalogField full htmlFor="preset-description" label="Description"><textarea id="preset-description" onChange={(e) => setDraft({ ...draft, description: e.currentTarget.value })} value={draft.description} /></CatalogField><CatalogToggle checked={draft.isPublic} description="La formule peut être projetée sur les parcours publics." label="Visible sur la vitrine" name="presetPublic" onChange={(value) => setDraft({ ...draft, isPublic: value })} /><CatalogField htmlFor="preset-order" label="Ordre"><input id="preset-order" min={0} onChange={(e) => setDraft({ ...draft, displayOrder: Number(e.currentTarget.value) })} type="number" value={draft.displayOrder} /></CatalogField></div></section><StickyActions busy={command.busy} dirty={dirty} onCancel={() => setDraft(saved)} /></form> : null}
    {tab === "composition" ? <FormulaComposition command={command} preset={preset} services={services} /> : null}
    {tab === "preview" ? <section className={styles.panel}><div className={styles.sectionHeading}><div><h2>Aperçu commercial</h2><p>Cette valeur vient de la projection Billing V2 publique, jamais d’une somme calculée dans le navigateur.</p></div>{preset.isPublic && preset.status === "active" ? <Link className="button button-secondary" href={`/formules/${encodeURIComponent(preset.code)}`}>Voir la formule publique</Link> : null}</div><div className={styles.priceHero}><div><StatusBadge label={baselineMonthlyAmountCents === null ? "Projection indisponible" : "Projection serveur"} tone={baselineMonthlyAmountCents === null ? "neutral" : "success"} /><strong className={styles.priceAmount}>{baselineMonthlyAmountCents === null ? "—" : `${formatCurrencyFromCents(baselineMonthlyAmountCents)} / mois`}</strong><p className={styles.hint}>Le montant affiché est la configuration recommandée courante. Les engagements et remises restent indépendants et sont appliqués par le devis serveur.</p></div><div className={styles.priceMeta}><strong>{preset.items.length} composant(s)</strong><span>{preset.isPublic ? "Visible sur la vitrine" : "Formule interne"}</span><Link className="text-link" href="/admin/public-pack-catalog">Gérer la présentation vitrine</Link><Link className="text-link" href="/admin/catalog?section=engagements">Consulter les engagements</Link></div></div></section> : null}
  </div>;
}

function FormulaComposition({ command, preset, services }: { command: ReturnType<typeof useAdminCatalogCommand>; preset: BillingV2AdminPreset; services: BillingV2AdminService[] }) {
  const [editing, setEditing] = useState<BillingV2AdminPresetItem | "new" | null>(null);
  const [item, setItem] = useState<ItemDraft>(() => emptyItem(services));
  const selectedService = services.find((service) => service.id === item.serviceId) ?? services[0];
  function beginCreate() { setItem(emptyItem(services)); setEditing("new"); }
  function beginEdit(entry: BillingV2AdminPresetItem) { setItem({ serviceId: entry.serviceId, tierId: entry.tierId ?? "", scopeTemplate: entry.scopeTemplate, quantity: entry.quantity, requiredItem: entry.requiredItem, customerEditable: entry.customerEditable, displayOrder: entry.displayOrder }); setEditing(entry); }
  async function submit(event: React.FormEvent) { event.preventDefault(); const payload = { presetId: preset.id, serviceId: item.serviceId, tierId: item.tierId || null, scopeTemplate: item.scopeTemplate, quantity: item.quantity, requiredItem: item.requiredItem, customerEditable: item.customerEditable, displayOrder: item.displayOrder }; const result = editing === "new" ? await command.send({ kind: "preset.item.add", ...payload }) : editing ? await command.send({ kind: "preset.item.update", itemId: editing.id, ...payload }) : null; if (result) setEditing(null); }
  return <section className={styles.panel}><div className={styles.sectionHeading}><div><h2>Composition</h2><p>Les composants décrivent la formule, sans stocker de total tarifaire.</p></div><button className="button" onClick={beginCreate} type="button">Ajouter un composant</button></div><div className={styles.stack}>{preset.items.map((entry) => <div className={styles.rowCard} key={entry.id}><div><strong>{entry.serviceCode}{entry.tierCode ? ` · ${entry.tierCode}` : ""}</strong><div className={styles.rowMeta}><span>{entry.scopeTemplate}</span><span>Quantité {entry.quantity}</span><span>{entry.requiredItem ? "Obligatoire" : "Optionnel"}</span><span>{entry.customerEditable ? "Modifiable" : "Figé"}</span></div></div><div className={styles.tableActions}><button className="button button-secondary button-small" onClick={() => beginEdit(entry)} type="button">Modifier</button><button className="table-action" disabled={command.busy} onClick={() => { if (window.confirm(`Retirer ${entry.serviceCode} de la formule ?`)) void command.send({ kind: "preset.item.remove", presetId: preset.id, itemId: entry.id }); }} type="button">Retirer</button></div></div>)}</div>
    {editing ? <form className={styles.inlineForm} onSubmit={submit}><div className={styles.fieldFull}><h3>{editing === "new" ? "Ajouter un composant" : "Modifier le composant"}</h3></div><CatalogField htmlFor="item-service" label="Service"><select id="item-service" onChange={(e) => setItem({ ...item, serviceId: e.currentTarget.value, tierId: "" })} value={item.serviceId}>{services.map((service) => <option key={service.id} value={service.id}>{service.name} ({service.code})</option>)}</select></CatalogField><CatalogField htmlFor="item-tier" label="Palier"><select id="item-tier" onChange={(e) => setItem({ ...item, tierId: e.currentTarget.value })} value={item.tierId}><option value="">Aucun</option>{selectedService?.tiers.map((tier) => <option key={tier.id} value={tier.id}>{tier.name} ({tier.code})</option>)}</select></CatalogField><CatalogField htmlFor="item-scope" label="Portée"><select id="item-scope" onChange={(e) => setItem({ ...item, scopeTemplate: e.currentTarget.value })} value={item.scopeTemplate}><option value="subscription">Abonnement</option><option value="primary_user">Utilisateur principal</option><option value="additional_user">Utilisateur supplémentaire</option></select></CatalogField><CatalogField htmlFor="item-quantity" label="Quantité"><input id="item-quantity" min={1} onChange={(e) => setItem({ ...item, quantity: Number(e.currentTarget.value) })} type="number" value={item.quantity} /></CatalogField><CatalogField htmlFor="item-order" label="Ordre"><input id="item-order" min={0} onChange={(e) => setItem({ ...item, displayOrder: Number(e.currentTarget.value) })} type="number" value={item.displayOrder} /></CatalogField><CatalogToggle checked={item.requiredItem} description="Ce composant ne peut pas être retiré de la formule." label="Obligatoire" name="itemRequired" onChange={(value) => setItem({ ...item, requiredItem: value })} /><CatalogToggle checked={item.customerEditable} description="Le client peut ajuster ce composant." label="Modifiable par le client" name="itemEditable" onChange={(value) => setItem({ ...item, customerEditable: value })} /><div className={`${styles.fieldFull} ${styles.actionGroup}`}><button className="button button-secondary" onClick={() => setEditing(null)} type="button">Annuler</button><button className="button" disabled={command.busy || services.length === 0} type="submit">Enregistrer le composant</button></div></form> : null}
  </section>;
}
function emptyItem(services: BillingV2AdminService[]): ItemDraft { return { serviceId: services[0]?.id ?? "", tierId: "", scopeTemplate: "subscription", quantity: 1, requiredItem: false, customerEditable: true, displayOrder: 0 }; }
