SELECT 'schema_migrations' AS metric, COUNT(*) AS value FROM schema_migrations;
SELECT migration_id FROM schema_migrations WHERE migration_id REGEXP '^(046|047|048|049|050|051|052|053|054|055|056)_' ORDER BY migration_id;
SELECT 'services' AS metric, COUNT(*) AS value FROM billing_v2_services;
SELECT 'tiers' AS metric, COUNT(*) AS value FROM billing_v2_service_tiers;
SELECT 'prices' AS metric, COUNT(*) AS value FROM billing_v2_service_prices;
SELECT 'presets' AS metric, COUNT(*) AS value FROM billing_v2_offer_presets;
SELECT 'preset_items' AS metric, COUNT(*) AS value FROM billing_v2_preset_items;
SELECT 'commitments' AS metric, COUNT(*) AS value FROM billing_v2_commitment_terms;
SELECT 'commitment_payment_options' AS metric, COUNT(*) AS value FROM billing_v2_commitment_payment_options;
SELECT 'legacy_pack_mappings' AS metric, COUNT(*) AS value FROM billing_v2_legacy_offer_mappings WHERE legacy_external_reference LIKE 'PACK-%';
SELECT 'legacy_service_mappings' AS metric, COUNT(*) AS value FROM billing_v2_legacy_service_mappings;
SELECT 'provisioning_rules' AS metric, COUNT(*) AS value FROM billing_v2_provisioning_rules;
SELECT 'provider_mappings' AS metric, COUNT(*) AS value FROM billing_v2_provider_price_mappings;
SELECT 'legacy_subscriptions' AS metric, COUNT(*) AS value FROM subscriptions;
SELECT 'v2_subscriptions' AS metric, COUNT(*) AS value FROM billing_v2_subscriptions;
SELECT 'commercial_documents' AS metric, COUNT(*) AS value FROM commercial_documents;
SELECT 'bpce_invoices' AS metric, COUNT(*) AS value FROM bpce_invoices;
SELECT 'provisioning_duplicate_precondition_rows' AS metric, COUNT(*) AS value FROM (SELECT subscription_id, action_type, target_type, target_reference, COUNT(*) c FROM subscription_provisioning_actions WHERE status IN ('pending','processing','completed') GROUP BY subscription_id, action_type, target_type, target_reference HAVING c > 1) dup;
SELECT 'outbox_duplicate_precondition_rows' AS metric, COUNT(*) AS value FROM (SELECT idempotency_key_hash, COUNT(*) c FROM billing_v2_outbox_events WHERE idempotency_key_hash IS NOT NULL GROUP BY idempotency_key_hash HAVING c > 1) dup;
SHOW CREATE TABLE billing_v2_subscription_documents;
SHOW CREATE TABLE billing_v2_document_line_snapshots;
SHOW INDEX FROM billing_v2_subscription_documents;
SHOW INDEX FROM billing_v2_document_line_snapshots;
