using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kermaria.ApiInternal.Services;

/// <summary>
/// Seed fermé du catalogue éditorial public. Les montants ne figurent pas ici :
/// Billing demeure la seule autorité numérique. Après le premier seed, la base
/// conserve toute modification effectuée depuis l'administration.
/// </summary>
internal static class StorefrontContentSeed
{
    private sealed record Link(string Label, string Href);
    private sealed record Section(string Heading, string BodyMarkdown);
    private sealed record Faq(string Question, string Answer);
    private sealed record ProblemEntry(string Title, string Description, string Href);
    private sealed record Page(
        string SeoTitle,
        string SeoDescription,
        string Title,
        string Lead,
        string CtaLabel,
        string CtaHref,
        IReadOnlyList<Section> Sections,
        IReadOnlyList<Faq> Faq,
        IReadOnlyList<Link> RelatedLinks,
        IReadOnlyList<ProblemEntry>? ProblemEntries = null);

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    public static string CreateJson(string key)
        => JsonSerializer.Serialize(Pages.TryGetValue(key, out var page)
            ? page
            : throw new PortalValidationException(), JsonOptions);

    private static readonly IReadOnlyDictionary<string, Page> Pages =
        new Dictionary<string, Page>(StringComparer.Ordinal)
        {
            ["storefront:services"] = PageOf(
                "Services IT gérés pour indépendants, associations et TPE | Zachary IT",
                "Messagerie, sauvegarde, accès distant, réseau, hébergement et support : partez de votre problème pour identifier le service IT adapté avec Zachary IT.",
                "L'informatique dont votre activité a besoin. Gérée pour vous.",
                "Un problème de messagerie, des données à protéger, un accès distant à organiser, un Wi-Fi instable ou un serveur à maintenir ? Partez de votre besoin : Zachary IT vous oriente vers la solution adaptée.",
                "Demander un audit", "/diagnostic",
                [
                    S("Des services modulaires, pas un catalogue figé", "Vous pouvez confier une brique précise ou un ensemble cohérent. Le périmètre est défini selon votre besoin, l'existant et les dépendances utiles ; les prestations nécessitant une étude restent traitées sur devis."),
                ],
                [F("Puis-je choisir un seul service ?", "Oui. Les services sont modulaires ; les dépendances éventuelles sont expliquées avant la mise en place."), F("Tout est-il commandable en ligne ?", "Non. Les services nécessitant une étude, une migration ou une mise en service restent traités par devis."), F("À qui s'adressent ces services ?", "Aux indépendants, associations, TPE et petites structures qui veulent déléguer une informatique utile et maintenable.")],
                [L("Cloud & Hébergement", "/services/cloud-hebergement"), L("Domaines & Messagerie", "/services/domaines-messagerie"), L("Réseau & Sécurité", "/services/reseau-securite"), L("Support & IT", "/services/support-it")],
                problemEntries:
                [
                    P("Mes emails posent problème", "Spam, migration, domaine, comptes ou configuration : identifiez le bon point de départ pour remettre la messagerie au propre.", "/services/messagerie-professionnelle"),
                    P("Je veux protéger mes données", "Sauvegarde, restauration et conservation : protégez les fichiers importants avec une stratégie adaptée à leur usage.", "/services/sauvegarde-externalisee"),
                    P("Je dois travailler à distance", "VPN et bureau Windows distant ne répondent pas au même besoin. Comparez les deux approches avant de choisir.", "/vpn-ou-bureau-a-distance-que-choisir"),
                    P("Mon réseau ou mon Wi-Fi fonctionne mal", "Coupures, couverture, lenteurs ou segmentation : partez des usages réels pour fiabiliser le réseau et le Wi-Fi.", "/services/unifi"),
                    P("J'ai un serveur, un site ou une application à maintenir", "Hébergement, mises à jour, supervision et sauvegarde : identifiez les briques à suivre pour garder le service maintenable.", "/services/cloud-hebergement"),
                    P("Je veux déléguer mon informatique", "Support, maintenance, supervision et coordination : confiez le quotidien IT avec un périmètre clair et adapté à votre structure.", "/services/support-it"),
                ]),
            ["storefront:tarifs"] = PageOf(
                "Tarifs des services IT : unités et devis",
                "Comprenez les unités de facturation des services Zachary IT : domaine, utilisateur, site, serveur ou instance. Les prestations étudiées restent sur devis.",
                "Des tarifs lisibles, sans faire croire qu’un service sur mesure est instantané.",
                "Les prix affichés correspondent aux services proposés. Les services de mise en place, migration, réseau ou infogérance restent qualifiés avant devis.",
                "Demander un devis", "/contact",
                [
                    S("Comment lire les unités", "Selon le service, la facturation peut être exprimée par domaine, utilisateur, site, serveur ou instance et par mois. Le montant affiché correspond au service et à son unité de facturation."),
                    S("Prestations sur devis", "Un domaine géré, une migration de messagerie, un réseau UniFi, une sécurité firewall, une reprise de serveur ou une infogérance nécessitent de confirmer le périmètre, les accès et les frais de fournisseurs éventuels."),
                    S("Formules et services", "Les formules sont des offres prêtes à l’emploi et configurables. Elles ne remplacent pas l’ensemble des services Zachary IT."),
                ],
                [F("Pourquoi certains services n’ont-ils pas de prix affiché ?", "Ils dépendent du périmètre réel, de l’existant et parfois de licences ou fournisseurs séparés."), F("Les prix affichés permettent-ils de commander ?", "Seulement quand le parcours indique explicitement qu’il est disponible. Sinon, le bon CTA est une demande de devis ou d’audit."), F("Une licence Microsoft 365 est-elle incluse ?", "Non par défaut : les licences provider sont précisées séparément dans le devis quand elles sont nécessaires.")],
                [L("Voir les formules", "/formules"), L("Demander un diagnostic", "/diagnostic"), L("Nous contacter", "/contact")]),
            ["storefront:cloud-hebergement"] = Category(
                "Cloud & Hébergement gérés | VPS, web, sauvegarde et supervision",
                "VPS, hébergement web, maintenance Linux et CMS, sauvegarde externe et supervision : Zachary IT met en place et suit vos services hébergés.",
                "Cloud & Hébergement : vos services restent suivis, pas simplement déposés chez un fournisseur.",
                "VPS Zachary IT, VPS Cloud, hébergement web, maintenance, sauvegarde externe et supervision : chaque brique est cadrée selon ce qui doit rester disponible.",
                "Voir les services cloud", "/services/vps",
                "VPS et hébergement", "Un VPS Zachary IT ou un VPS Cloud peut être préparé et géré ; les caractéristiques CPU, RAM et stockage sont celles affichées sur chaque offre. Lorsque le parcours le permet, la commande peut être payée en ligne, puis la mise en service intervient après validation technique.",
                "Maintenance, sauvegarde et suivi", "Mises à jour Linux ou CMS, copie séparée, tests de restauration et alertes utiles complètent l’hébergement. Une sauvegarde sans suivi ne remplace pas la supervision.",
                [L("VPS", "/services/vps"), L("Hébergement web", "/services/hebergement-web"), L("Sauvegarde externalisée", "/services/sauvegarde-externalisee"), L("Supervision informatique", "/services/supervision-informatique")]),
            ["storefront:domaines-messagerie"] = Category(
                "Domaines et messagerie professionnelle | Zachary IT",
                "Gestion de domaines, DNS, messagerie professionnelle, migration et réglages SPF, DKIM et DMARC pour les petites structures.",
                "Domaines & Messagerie : votre identité numérique reste administrée et compréhensible.",
                "Zachary IT gère les domaines, les zones DNS, les boîtes professionnelles et les migrations en clarifiant les accès, les licences et les responsabilités.",
                "Parler de ma messagerie", "/contact",
                "Domaine, DNS et responsabilités", "DOMAIN-MANAGED est un service public traité sur devis. La gestion inclut le suivi des réglages et des accès, sans inventer de cadence annuelle ni de prix fournisseur inclus.",
                "Messagerie et délivrabilité", "Boîtes mail, Microsoft 365, migration et SPF, DKIM ou DMARC sont préparés selon l’existant. Ces réglages réduisent des risques ; ils ne garantissent jamais la délivrabilité.",
                [L("Gestion DNS et domaines", "/services/gestion-dns-domaines"), L("Messagerie professionnelle", "/services/messagerie-professionnelle"), L("Demander un audit", "/diagnostic")]),
            ["storefront:reseau-securite"] = Category(
                "Réseau et sécurité gérés | VPN, UniFi, firewall et WAF",
                "VPN entreprise, Wi-Fi UniFi, firewall, Cloudflare WAF et supervision : Zachary IT conçoit et suit des accès adaptés à votre activité.",
                "Réseau & Sécurité : des accès utiles, protégés et maintenables.",
                "Accès distant, Wi-Fi, segmentation, firewall, protection web et supervision sont articulés autour de vos usages plutôt que d’une accumulation de produits.",
                "Demander un audit réseau", "/diagnostic",
                "Accès et réseau local", "VPN, bureau Windows distant, UniFi, Wi-Fi et segmentation sont distingués pour choisir le bon mode d’accès. Une intervention tient compte du réseau existant et de sa capacité d’évolution.",
                "Protection et suivi", "Firewall, Cloudflare WAF et supervision limitent l’exposition et rendent les incidents plus visibles. Ils ne constituent ni une sécurité absolue ni une promesse de disponibilité sans interruption.",
                [L("VPN entreprise", "/services/vpn-entreprise"), L("UniFi", "/services/unifi"), L("Firewall", "/services/firewall"), L("Cloudflare WAF", "/services/cloudflare-waf")]),
            ["storefront:support-it"] = Category(
                "Support et infogérance IT | Zachary IT",
                "Assistance utilisateurs, maintenance des postes, infogérance et migrations : Zachary IT organise et suit votre informatique au quotidien.",
                "Support & IT : une assistance qui traite le quotidien et prépare la suite.",
                "Zachary IT intervient pour l’assistance, les postes, les évolutions et la coordination technique, avec un périmètre explicite plutôt qu’une promesse de support illimité.",
                "Demander un diagnostic", "/diagnostic",
                "Assistance et maintenance", "Les utilisateurs disposent d’un interlocuteur pour les incidents et les usages courants. Les mises à jour, postes et services associés sont traités dans le périmètre retenu.",
                "Infogérance et projets", "Une reprise de parc, une migration ou l’infogérance d’un serveur se préparent avec un état des lieux. Les urgences, opérations hors périmètre et licences sont identifiées avant intervention.",
                [L("Infogérance VPS", "/services/infogerance-vps"), L("Maintenance Linux", "/services/maintenance-linux"), L("Bureau Windows à distance", "/services/bureau-windows-distance"), L("Nous contacter", "/contact")]),
            ["storefront:vps"] = Seo("VPS géré : hébergement et administration | Zachary IT", "Choisissez un VPS Zachary IT, un VPS Cloud ou une infogérance VPS. Zachary IT cadre l’hébergement, la maintenance, la sauvegarde et le suivi.", "VPS géré pour votre activité", "Un serveur virtuel peut héberger un site, une application ou un service métier. Zachary IT distingue le VPS fourni, le VPS Cloud et l’infogérance d’un serveur existant.", "Demander un devis", "/contact", "VPS Zachary IT, VPS Cloud et infogérance", "Le VPS Zachary IT et le VPS Cloud ne recouvrent pas la même mise en œuvre. Les caractéristiques CPU, RAM et stockage sont celles affichées sur chaque offre. Lorsque le parcours le permet, la commande peut être payée en ligne, puis la mise en service intervient après validation technique. L’infogérance peut aussi porter sur un VPS chez un autre fournisseur.", "Ce qui est cadré avant mise en service", "Usages, données, accès, sauvegarde, maintenance, dépendances et responsabilité du fournisseur sont qualifiés avant la mise en service. L’infogérance peut aussi porter sur un VPS chez un autre fournisseur.", [F("Puis-je garder mon hébergeur ?", "Oui, l’infogérance VPS peut être étudiée sur un serveur existant."), F("Le VPS Cloud est-il créé instantanément ?", "Non. Sa mise en service est organisée après validation technique."), F("Une sauvegarde est-elle incluse ?", "Elle dépend du périmètre retenu et doit être explicitement prévue.")], [L("Infogérance VPS", "/services/infogerance-vps"), L("Sauvegarde externalisée", "/services/sauvegarde-externalisee"), L("Maintenance Linux", "/services/maintenance-linux")]),
            ["storefront:infogerance-vps"] = Seo("Infogérance VPS : maintenance de serveur existant | Zachary IT", "Confiez la maintenance et le suivi de votre VPS existant à Zachary IT, y compris chez un fournisseur tiers après cadrage.", "Infogérance VPS : qui gère votre serveur au quotidien ?", "Zachary IT peut reprendre l’administration d’un VPS déjà hébergé chez un fournisseur tiers, après vérification des accès, de l’état du système et des dépendances.", "Demander un audit VPS", "/diagnostic", "Maintenance et suivi du serveur", "Mises à jour, surveillance des erreurs, sauvegarde, accès d’administration et documentation sont organisés selon le périmètre. L’infogérance ne supprime pas les obligations du fournisseur d’hébergement.", "En cas d’incident", "Les alertes et contacts sont définis avant la reprise. Les délais, horaires et opérations exceptionnelles sont précisés au devis ; aucun support continu non contracté n’est implicite.", [F("Puis-je conserver mon fournisseur ?", "Oui, si les accès et conditions permettent une administration responsable."), F("Que comprend la maintenance ?", "Le détail dépend du serveur ; mises à jour, surveillance et sauvegardes sont cadrées avant démarrage."), F("Zachary IT peut-il reprendre un serveur non documenté ?", "Une phase d’audit est nécessaire pour mesurer le risque et proposer une reprise réaliste.")], [L("VPS", "/services/vps"), L("Maintenance Linux", "/services/maintenance-linux"), L("Supervision informatique", "/services/supervision-informatique")]),
            ["storefront:hebergement-web"] = Seo("Hébergement web géré et maintenance de site | Zachary IT", "Hébergement web, déploiement, mises à jour et suivi de site : Zachary IT prépare un service maintenable selon votre CMS et vos usages.", "Hébergement web géré pour un site qui reste maintenable", "Un site public dépend de son hébergement, de ses mises à jour, de ses accès et de ses sauvegardes. Zachary IT aide à organiser ces éléments sans masquer les limites du CMS existant.", "Demander un devis", "/contact", "Mettre un site en ligne et le suivre", "L’hébergement comprend le cadrage du domaine, du déploiement, des accès et des mises à jour nécessaires. Les performances, extensions et dépendances du site existant sont vérifiées avant toute promesse.", "CMS, sauvegarde et sécurité", "La maintenance peut couvrir un CMS, ses extensions et les correctifs nécessaires. Une protection web ou une sauvegarde sont des briques séparées, choisies selon le risque et le contenu à protéger.", [F("Puis-je garder mon CMS actuel ?", "Oui, après analyse de son état, de ses extensions et de ses accès."), F("Un hébergement garantit-il que le site ne tombera jamais ?", "Non. Le suivi réduit les risques mais ne permet pas de promettre une disponibilité absolue."), F("La maintenance WordPress est-elle incluse ?", "Elle fait l’objet d’un périmètre distinct selon le site.")], [L("Maintenance WordPress", "/services/maintenance-wordpress"), L("Cloudflare WAF", "/services/cloudflare-waf"), L("Gestion DNS et domaines", "/services/gestion-dns-domaines")]),
            ["storefront:maintenance-linux"] = Seo("Maintenance Linux : mises à jour et suivi de serveur | Zachary IT", "Zachary IT assure la maintenance Linux de serveurs existants : mises à jour, suivi des erreurs, sauvegarde et interventions cadrées.", "Maintenance Linux pour ne pas laisser un serveur s’user en silence", "Un serveur Linux a besoin de mises à jour, de contrôle des erreurs, d’accès maîtrisés et d’une stratégie de sauvegarde. Zachary IT intervient sur un périmètre documenté.", "Demander un audit serveur", "/diagnostic", "Ce que couvre une maintenance Linux", "Le périmètre peut inclure les correctifs système, les journaux utiles, l’état des services et les alertes. Les applications métier, versions anciennes ou changements majeurs sont qualifiés séparément.", "Garder son hébergeur et gérer un incident", "Vous pouvez conserver votre fournisseur si les accès permettent une intervention. En cas d’incident, le mode de contact, les sauvegardes et les limites de responsabilité sont établis au préalable.", [F("Qui met à jour mon serveur ?", "Zachary IT peut le faire dans le cadre d’une maintenance définie."), F("Les erreurs sont-elles surveillées ?", "Les signaux retenus dépendent du service et de la supervision prévue."), F("Puis-je conserver mon hébergeur ?", "Oui, sous réserve d’accès et de conditions compatibles avec l’infogérance.")], [L("Infogérance VPS", "/services/infogerance-vps"), L("Supervision informatique", "/services/supervision-informatique"), L("Sauvegarde externalisée", "/services/sauvegarde-externalisee")]),
            ["storefront:maintenance-wordpress"] = Seo("Maintenance WordPress : mises à jour, sauvegarde et sécurité | Zachary IT", "Zachary IT maintient votre site WordPress : mises à jour, extensions, sauvegarde et diagnostic des risques avant intervention.", "Maintenance WordPress : garder votre site à jour sans improviser", "Un site WordPress dépend du cœur, des extensions, du thème, de l’hébergement et des accès. Zachary IT vérifie cet ensemble avant de définir une maintenance.", "Demander un audit WordPress", "/diagnostic", "Mises à jour et compatibilité", "Les mises à jour sont préparées en tenant compte des extensions et du thème. Une extension abandonnée, une personnalisation fragile ou un hébergement ancien peut nécessiter une correction préalable.", "Sauvegarde et protection", "Une copie restaurable est distincte de la synchronisation de fichiers. La protection WAF ou les réglages DNS peuvent compléter la maintenance, mais ne garantissent pas l’absence de vulnérabilité.", [F("Mettez-vous à jour toutes les extensions ?", "Le périmètre est évalué selon leur état, leur compatibilité et leur criticité."), F("Pouvez-vous reprendre un site créé par un autre prestataire ?", "Oui, après audit des accès, du code et de l’hébergement."), F("Une maintenance inclut-elle une refonte ?", "Non, une refonte ou une évolution importante fait l’objet d’un projet distinct.")], [L("Hébergement web", "/services/hebergement-web"), L("Sauvegarde externalisée", "/services/sauvegarde-externalisee"), L("Cloudflare WAF", "/services/cloudflare-waf")]),
            ["storefront:sauvegarde-externalisee"] = Seo("Sauvegarde externalisée : copie séparée et restauration | Zachary IT", "Protégez vos données avec une sauvegarde externalisée, une copie séparée, des restaurations préparées et une supervision adaptée.", "Sauvegarde externalisée : une copie séparée, utile le jour où il faut restaurer", "Une synchronisation propage aussi une suppression ou une erreur. Une sauvegarde conserve une copie distincte et doit être pensée avec la restauration et la supervision.", "Demander un audit sauvegarde", "/diagnostic", "Sauvegarde, synchronisation et restauration", "Zachary IT identifie les données à protéger, la copie séparée, les accès et les conditions de restauration. La durée de conservation et le périmètre sont annoncés dans l’offre adaptée.", "Pourquoi la supervision compte", "Une sauvegarde qui échoue sans alerte ne protège pas l’activité. Les contrôles et notifications utiles font partie du cadrage, sans promettre qu’aucune perte de données ne puisse survenir.", [F("Une synchronisation est-elle une sauvegarde ?", "Non. Elle ne protège pas nécessairement contre les suppressions ou altérations propagées."), F("Pouvez-vous restaurer mes données ?", "La restauration dépend de la copie, des données concernées et du périmètre prévu."), F("La sauvegarde est-elle liée à un serveur précis ?", "Elle peut couvrir différents environnements après qualification.")], [L("Supervision informatique", "/services/supervision-informatique"), L("VPS", "/services/vps"), L("Hébergement web", "/services/hebergement-web")]),
            ["storefront:supervision-informatique"] = Seo("Supervision informatique : alertes et suivi des services | Zachary IT", "Zachary IT met en place une supervision informatique pour suivre les services, détecter les alertes utiles et organiser les premières actions.", "Supervision informatique : voir les signaux utiles avant qu’ils bloquent l’activité", "La supervision suit des services, équipements ou sauvegardes selon un périmètre défini. Elle transforme des signaux techniques en alertes exploitables, sans remplacer une intervention humaine.", "Demander un audit", "/diagnostic", "Ce qui peut être supervisé", "Serveurs, sites, sauvegardes, NAS, réseau ou services hébergés peuvent être inclus selon les accès et les besoins. Les seuils et destinataires des alertes sont définis avec vous.", "De l’alerte à l’action", "Recevoir une alerte ne suffit pas : le plan précise qui est contacté, ce qui est vérifié et ce qui relève d’une intervention supplémentaire. Aucune surveillance ne garantit l’absence d’incident.", [F("La supervision répare-t-elle automatiquement ?", "Non, elle détecte et signale ; les actions dépendent du service et du périmètre."), F("Puis-je superviser un NAS ?", "Oui, après vérification de l’équipement et des accès."), F("Les alertes arrivent-elles à toute heure ?", "Les modalités de notification sont définies dans le périmètre retenu.")], [L("Supervision NAS", "/services/supervision-nas"), L("Sauvegarde externalisée", "/services/sauvegarde-externalisee"), L("Maintenance Linux", "/services/maintenance-linux")], pricingBody: "Le tarif dépend du nombre d’équipements ou de services à superviser, des accès nécessaires et du niveau de suivi attendu. Lorsque le prix ne peut pas être déterminé immédiatement, nous vous proposons un devis adapté à votre besoin."),
            ["storefront:supervision-nas"] = Seo("Supervision NAS : suivi du stockage et des sauvegardes | Zachary IT", "Zachary IT supervise votre NAS pour suivre les alertes de stockage, la disponibilité et les sauvegardes prévues.", "Supervision NAS : ne pas découvrir un problème de stockage trop tard", "Un NAS peut concentrer des fichiers essentiels et des sauvegardes. Zachary IT aide à suivre les alertes utiles, l’espace, les services exposés et les copies prévues.", "Demander un audit NAS", "/diagnostic", "Suivre le NAS et ses signaux", "La supervision dépend du modèle, des accès et des services activés. Elle peut couvrir la disponibilité, l’état de stockage ou les sauvegardes, sans se substituer au constructeur ni à une stratégie de restauration.", "NAS, sauvegarde et accès distant", "Un NAS exposé sans contrôle crée un risque. Les accès distants, VPN, droits utilisateurs et copie externe sont étudiés ensemble lorsque les données sont sensibles.", [F("Un NAS est-il une sauvegarde à lui seul ?", "Non. Il peut être le stockage principal ou une copie locale ; une séparation supplémentaire peut être nécessaire."), F("Pouvez-vous surveiller un NAS existant ?", "Oui, après vérification du modèle, des accès et du périmètre."), F("Faut-il ouvrir le NAS sur Internet ?", "Pas par défaut ; un accès VPN ou une solution adaptée est étudié selon l’usage.")], [L("Sauvegarde externalisée", "/services/sauvegarde-externalisee"), L("VPN entreprise", "/services/vpn-entreprise"), L("Supervision informatique", "/services/supervision-informatique")]),
            ["storefront:vpn-entreprise"] = Seo("VPN entreprise : accès distant sécurisé | Zachary IT", "Accédez à vos fichiers, applications et équipements depuis l’extérieur sans les exposer directement sur Internet avec un VPN d’entreprise cadré.", "Accès VPN sécurisé pour votre entreprise", "Accédez à vos fichiers, applications et équipements depuis l’extérieur sans les exposer directement sur Internet. Zachary IT configure un VPN adapté aux utilisateurs et aux ressources concernées.", "Demander un audit réseau", "/diagnostic", "À quoi sert un VPN ?", "Un VPN crée un accès privé entre un appareil autorisé et le réseau ou service visé. Il convient pour rejoindre des ressources internes, sans transformer chaque usage distant en accès public.", "VPN ou bureau Windows distant ?", "Le VPN donne accès à un réseau ou à des ressources autorisées ; un bureau Windows distant fournit un environnement Windows exécuté à distance. Le bon choix dépend des applications, données et postes utilisés.", [F("Le VPN donne-t-il accès à tout le réseau ?", "Non, les droits et segments accessibles sont définis selon les utilisateurs."), F("Puis-je me connecter depuis plusieurs appareils ?", "Cela dépend de la politique d’accès et des appareils autorisés."), F("Un VPN rend-il tout sécurisé ?", "Il réduit l’exposition de certains accès mais doit être associé à des comptes, règles et mises à jour adaptés.")], [L("Bureau Windows à distance", "/services/bureau-windows-distance"), L("Firewall", "/services/firewall"), L("UniFi", "/services/unifi")]),
            ["storefront:bureau-windows-distance"] = Seo("Bureau Windows à distance pour travailler partout | Zachary IT", "Utilisez un bureau Windows distant depuis plusieurs appareils, avec un accès cadré, un stockage associé et les options de sauvegarde adaptées.", "Bureau Windows à distance : retrouver son environnement de travail depuis ailleurs", "Un bureau Windows distant permet d’utiliser un environnement Windows hébergé depuis un appareil autorisé. Il ne doit pas être confondu avec un simple VPN.", "Demander un devis", "/contact", "Bureau distant ou VPN", "Le VPN rejoint des ressources internes ; le bureau Windows distant exécute les applications dans un environnement Windows à distance. Zachary IT vous aide à choisir selon les logiciels, utilisateurs et données.", "Stockage, sauvegarde et accès", "Les données, profils, droits d’accès et besoins de sauvegarde sont précisés avant mise en service. Les licences Microsoft ou fournisseur nécessaires ne sont pas supposées incluses.", [F("Puis-je utiliser un Mac ou une tablette ?", "L’accès dépend des appareils, logiciels et politiques retenus."), F("Mes fichiers sont-ils sauvegardés ?", "Cela dépend du stockage et de la sauvegarde explicitement prévus."), F("Est-ce un configurateur de formule ?", "Non. Cette page explique le service ; les formules restent sur leur parcours dédié.")], [L("VPN entreprise", "/services/vpn-entreprise"), L("Sauvegarde externalisée", "/services/sauvegarde-externalisee"), L("Tarifs", "/tarifs")]),
            ["storefront:unifi"] = Seo("Réseau UniFi : Wi-Fi, switching et supervision | Zachary IT", "Conception, évolution et maintenance de réseau UniFi : Wi-Fi, switching, segmentation, supervision et documentation utiles.", "Réseau UniFi : Wi-Fi, switching et évolution de votre installation", "Zachary IT conçoit, reprend ou fait évoluer une installation UniFi en tenant compte des locaux, utilisateurs, équipements et usages critiques.", "Demander un audit réseau", "/diagnostic", "Wi-Fi, switching et segmentation", "Le réseau peut séparer les usages, équipements et invités lorsque cela répond à un besoin réel. La couverture Wi-Fi, les switches et les points d’accès sont étudiés sur site ou à partir des informations disponibles.", "Maintenance et supervision", "Les accès d’administration, mises à jour, documentation et alertes sont organisés pour que l’installation reste maintenable et évolutive. Les performances radio dépendent aussi des locaux et de l’environnement.", [F("Pouvez-vous reprendre une installation UniFi existante ?", "Oui, après audit des équipements, comptes et configuration."), F("Le Wi-Fi couvre-t-il tous les locaux ?", "Une étude est nécessaire ; les matériaux et contraintes du lieu influencent le résultat."), F("La segmentation est-elle toujours nécessaire ?", "Elle est proposée lorsqu’elle améliore concrètement la sécurité ou l’exploitation.")], [L("VPN entreprise", "/services/vpn-entreprise"), L("Firewall", "/services/firewall"), L("Supervision informatique", "/services/supervision-informatique")]),
            ["storefront:firewall"] = Seo("Firewall entreprise : règles réseau et accès maîtrisés | Zachary IT", "Zachary IT configure et maintient un firewall pour maîtriser les accès réseau, les services exposés et les règles utiles à votre activité.", "Firewall : maîtriser les accès sans bloquer le travail", "Un firewall filtre les flux entre réseaux et vers Internet. Zachary IT définit des règles lisibles, liées aux usages et documentées pour faciliter la maintenance.", "Demander un audit", "/diagnostic", "Des règles adaptées aux services réellement utilisés", "Les ouvertures, VPN, postes, équipements et applications sont recensés avant configuration. Les exceptions sont limitées et expliquées ; une règle permissive n’est pas une solution durable.", "Maintenance et limites", "Les mises à jour, accès d’administration et évolutions sont suivis selon le périmètre. Un firewall ne protège pas seul contre tous les risques et ne remplace ni les sauvegardes ni les mises à jour.", [F("Pouvez-vous remplacer un firewall existant ?", "Oui, après analyse des règles, équipements et dépendances."), F("Faut-il ouvrir des ports pour travailler à distance ?", "Pas systématiquement ; un VPN ou une autre architecture peut éviter une exposition directe."), F("Le firewall protège-t-il contre toutes les attaques ?", "Non. Il fait partie d’un ensemble de mesures proportionnées.")], [L("VPN entreprise", "/services/vpn-entreprise"), L("Cloudflare WAF", "/services/cloudflare-waf"), L("UniFi", "/services/unifi")]),
            ["storefront:cloudflare-waf"] = Seo("Cloudflare WAF : protection de site web gérée | Zachary IT", "Protégez un site ou service web exposé avec Cloudflare WAF, DNS, règles adaptées et suivi des changements par Zachary IT.", "Cloudflare WAF : protéger un service web exposé sans promettre l’impossible", "Un WAF aide à filtrer certains trafics malveillants vers un site ou une application. Zachary IT configure les règles, DNS et accès nécessaires selon les usages légitimes.", "Demander un audit web", "/diagnostic", "DNS, WAF et règles de protection", "La mise en place commence par le domaine, les enregistrements DNS, l’origine du site et les flux attendus. Les règles sont ajustées pour limiter les faux positifs et rester compréhensibles.", "Ce que le WAF ne remplace pas", "Un WAF ne corrige pas un CMS non maintenu, une application vulnérable ou des accès administrateurs faibles. Il complète la maintenance, les mises à jour et les sauvegardes.", [F("Cloudflare WAF empêche-t-il toutes les attaques ?", "Non. Il réduit certains risques mais ne garantit pas une sécurité absolue."), F("Pouvez-vous gérer le DNS ?", "Oui, dans le cadre d’une gestion de domaine et de DNS cadrée."), F("Est-ce compatible avec WordPress ?", "Oui, après vérification de l’hébergement et des extensions.")], [L("Hébergement web", "/services/hebergement-web"), L("Maintenance WordPress", "/services/maintenance-wordpress"), L("Gestion DNS et domaines", "/services/gestion-dns-domaines")]),
            ["storefront:gestion-dns-domaines"] = Seo("Gestion DNS et domaines professionnels | Zachary IT", "Zachary IT gère domaines et DNS : accès, zones, transferts, messagerie et réglages utiles à votre présence en ligne.", "Gestion DNS et domaines : garder la maîtrise de votre identité en ligne", "Un nom de domaine, ses accès et sa zone DNS doivent rester identifiés, documentés et liés aux bons services. Zachary IT organise cette gestion sur devis.", "Demander un devis", "/contact", "Domaine, zone DNS et responsabilités", "La gestion couvre le suivi des enregistrements utiles au site, à la messagerie et aux services associés. Les comptes, contacts et règles de transfert sont clarifiés avant intervention.", "Ce qui n’est pas inventé", "Le domaine géré reste public mais non commandable en libre-service. Les frais de registre, de fournisseur ou de licence ne sont pas supposés inclus et aucune cadence annuelle n’est créée dans la vitrine.", [F("Pouvez-vous corriger une zone DNS existante ?", "Oui, après vérification des accès et de l’impact des enregistrements."), F("Puis-je garder mon registrar ?", "Oui, si les droits permettent une gestion sûre et documentée."), F("Le service inclut-il la messagerie ?", "Les réglages DNS peuvent servir la messagerie ; les boîtes et licences sont un périmètre distinct.")], [L("Messagerie professionnelle", "/services/messagerie-professionnelle"), L("Cloudflare WAF", "/services/cloudflare-waf"), L("Hébergement web", "/services/hebergement-web")]),
            ["storefront:messagerie-professionnelle"] = Seo("Messagerie professionnelle : boîtes mail, migration et DNS | Zachary IT", "Messagerie professionnelle, Microsoft 365, migration, SPF, DKIM et DMARC : Zachary IT organise votre e-mail et les réglages techniques associés.", "Messagerie professionnelle : des boîtes mail et des réglages qui restent maîtrisés", "Zachary IT accompagne la mise en place, la migration et l’administration technique d’une messagerie professionnelle, avec une distinction claire entre service, licences et configuration DNS.", "Demander un audit messagerie", "/diagnostic", "Boîtes mail, Microsoft 365 et migration", "Le nombre de boîtes, les adresses, les données à reprendre et les usages sont qualifiés avant migration. Les licences Microsoft 365 ou d’un autre fournisseur sont précisées séparément lorsqu’elles sont nécessaires.", "SPF, DKIM et DMARC", "Ces enregistrements DNS aident à authentifier les messages et à réduire l’usurpation. Ils ne garantissent pas que chaque message sera délivré et nécessitent d’être alignés avec les services réellement émetteurs.", [F("Une messagerie professionnelle inclut-elle Microsoft 365 ?", "Pas automatiquement : les licences provider sont indiquées séparément."), F("Pourquoi mes mails arrivent-ils en spam ?", "Les réglages DNS, la réputation et le contenu peuvent jouer ; un audit permet de vérifier SPF, DKIM et DMARC."), F("Pouvez-vous migrer mes anciennes boîtes ?", "Oui, après qualification des comptes, volumes et contraintes d’accès.")], [L("Gestion DNS et domaines", "/services/gestion-dns-domaines"), L("Cloudflare WAF", "/services/cloudflare-waf"), L("Nous contacter", "/contact")]),
        };

    private static Page Category(string seoTitle, string seoDescription, string title, string lead, string ctaLabel, string ctaHref, string firstHeading, string firstBody, string secondHeading, string secondBody, IReadOnlyList<Link> links)
        => PageOf(seoTitle, seoDescription, title, lead, ctaLabel, ctaHref,
            [S(firstHeading, firstBody), S(secondHeading, secondBody), S("Pour avancer", "Consultez une page de service précise ou demandez un audit : la proposition tiendra compte de l’existant, des contraintes et du périmètre utile.")],
            [F("Ces services sont-ils disponibles en libre-service ?", "Seulement lorsque le parcours le précise. Les prestations nécessitant une étude restent sur devis."), F("Puis-je demander un seul service ?", "Oui. Les dépendances éventuelles sont expliquées avant la mise en place."), F("Comment commencer ?", "Choisissez une page liée ou utilisez le diagnostic pour décrire votre besoin.")], links);

    private static Page Seo(string seoTitle, string seoDescription, string title, string lead, string ctaLabel, string ctaHref, string firstHeading, string firstBody, string secondHeading, string secondBody, IReadOnlyList<Faq> faq, IReadOnlyList<Link> links, string? pricingBody = null)
        => PageOf(seoTitle, seoDescription, title, lead, ctaLabel, ctaHref,
            [S(firstHeading, firstBody), S(secondHeading, secondBody), S("Tarif et devis", pricingBody ?? "Le service est qualifié avant mise en œuvre. Lorsque le prix ne peut pas être déterminé immédiatement, nous vous proposons un devis adapté à votre besoin.")], faq, links);

    private static Page PageOf(string seoTitle, string seoDescription, string title, string lead, string ctaLabel, string ctaHref, IReadOnlyList<Section> sections, IReadOnlyList<Faq> faq, IReadOnlyList<Link> links, IReadOnlyList<ProblemEntry>? problemEntries = null)
        => new(seoTitle, seoDescription, title, lead, ctaLabel, ctaHref, sections, faq, links, problemEntries);

    private static Section S(string heading, string body) => new(heading, body);
    private static Faq F(string question, string answer) => new(question, answer);
    private static Link L(string label, string href) => new(label, href);
    private static ProblemEntry P(string title, string description, string href) => new(title, description, href);
}
